let state={phone:localStorage.getItem("pc_phone")||"",token:localStorage.getItem("pc_token")||"",otpPhone:null,pinId:null,demoCode:null,user:JSON.parse(localStorage.getItem("pc_user")||"null")};
const $=id=>document.getElementById(id);
function toast(t){const e=$("toast");e.textContent=t;e.style.display="block";setTimeout(()=>e.style.display="none",3000)}
function go(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");$("nav").style.display=state.token?"grid":"none";if(id==="dashboard")renderUser();if(id==="history")loadHistory();if(id==="profile")renderUser();scrollTo({top:0,behavior:"smooth"})}
function norm(p){return String(p||"").replace(/\s+/g,"").replace(/^\+225/,'').replace(/^225/,'')}
function msg(id,t,err=false){$(id).textContent=t;$(id).className=err?"small err":"small"}
async function post(url,body){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json",...(state.token?{Authorization:`Bearer ${state.token}`}:{})},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||"Erreur");return d}
async function requestOtp(){const phone=norm($("phone").value);if(!/^(05|07|01)\d{8}$/.test(phone))return msg("registerMsg","Numéro ivoirien invalide.",true);try{const d=await post("/api/auth/request-otp",{phone});state.otpPhone=phone;state.pinId=d.pinId||null;state.demoCode=d.demoCode||null;msg("otpMsg",d.demo?`Démo : ton code est ${d.demoCode}`:"Code envoyé par SMS.");go("otp")}catch(e){msg("registerMsg",e.message,true)}}
async function loginRequest(){const phone=norm($("loginPhone").value);if(!/^(05|07|01)\d{8}$/.test(phone))return msg("loginMsg","Numéro ivoirien invalide.",true);try{const d=await post("/api/auth/request-otp",{phone});state.otpPhone=phone;state.pinId=d.pinId||null;state.demoCode=d.demoCode||null;msg("otpMsg",d.demo?`Démo : ton code est ${d.demoCode}`:"Code envoyé par SMS.");go("otp")}catch(e){msg("loginMsg",e.message,true)}}
async function verifyOtp(){const pin=$("otpCode").value.trim();if(!/^\d{4,8}$/.test(pin))return msg("otpMsg","Entre le code reçu.",true);try{const d=await post("/api/auth/verify-otp",{phone:state.otpPhone,pin,pinId:state.pinId});state.token=d.token;state.user=d.user;state.phone=d.user.phone;localStorage.setItem("pc_token",state.token);localStorage.setItem("pc_user",JSON.stringify(state.user));localStorage.setItem("pc_phone",state.phone);toast("Compte vérifié ✅");go("dashboard")}catch(e){msg("otpMsg",e.message,true)}}
function renderUser(){if(!state.user)return;$("balance").textContent=`${Number(state.user.balance||0).toLocaleString("fr-FR")} FCFA`;$("profilePhone").textContent=`+225 ${state.user.phone}`;$("profileName").textContent=state.user.name||"Mon compte"}
async function prepareRecharge(){const recipient=norm($("recipient").value),operator=$("operator").value,amount=Number($("amount").value);msg("sendMsg","Préparation du paiement...");try{const d=await post("/api/recharges/prepare",{recipient,operator,amount});state.order=d.order;localStorage.setItem("pc_order",JSON.stringify(d.order));$("orderInfo").textContent=`${amount.toLocaleString("fr-FR")} FCFA → +225 ${recipient}`;$("payStatus").textContent=d.demo?"Mode démo : aucun argent réel ne sera débité.":(d.payment?.checkout_url?"Une page de paiement va s'ouvrir.":"Une demande de paiement arrive sur ton téléphone.");go("payment")}catch(e){msg("sendMsg",e.message,true)}}
async function confirmDemo(){try{const d=await post(`/api/recharges/${state.order.id}/demo-complete`,{});state.order=d.order;toast("Recharge simulée réussie ✅");go("success")}catch(e){toast(e.message)}}
async function refreshOrder(){try{const d=await fetch(`/api/recharges/${state.order.id}`,{headers:{Authorization:`Bearer ${state.token}`}}).then(r=>r.json());if(d.ok){state.order=d.order;$("payStatus").textContent=`Statut : ${d.order.status}`;if(d.order.status==="SUCCESS")go("success")}}catch{}}
function renderHistory(){return}
async function loadHistory(){const e=$("historyList");e.innerHTML='<div class="card small">Chargement...</div>';try{const d=await fetch('/api/history',{headers:{Authorization:`Bearer ${state.token}`}}).then(r=>r.json());if(!d.orders?.length){e.innerHTML='<div class="card small">Aucune recharge.</div>';return}e.innerHTML=d.orders.map(o=>`<div class="item"><div><b>+225 ${o.recipient}</b><div class="small">${o.operator} · ${new Date(o.createdAt).toLocaleString('fr-FR')}</div></div><div class="right"><b>${Number(o.amount).toLocaleString('fr-FR')} F</b><span class="status">${o.status}</span></div></div>`).join('')}catch{e.innerHTML='<div class="card err">Erreur de chargement.</div>'}}
function logout(){localStorage.clear();state={phone:"",token:"",otpPhone:null,pinId:null,demoCode:null,user:null};go("welcome")}
if(state.token)go("dashboard");else go("welcome");
