import React, {useEffect, useMemo, useState} from 'react';
import {Alert, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Clipboard from 'expo-clipboard';
import {StatusBar} from 'expo-status-bar';

const GREEN='#63ff22', BG='#071326', CARD='#0e1d35', CARD2='#122542', MUTED='#aebbd0', LINE='#233652';
const DEMO='1234';

function Button({title,onPress,primary=false}){return <TouchableOpacity onPress={onPress} style={[styles.btn,primary?styles.primary:styles.secondary]}><Text style={[styles.btnText,primary&&styles.primaryText]}>{title}</Text></TouchableOpacity>}
function Card({children}){return <View style={styles.card}>{children}</View>}

export default function App(){
 const [screen,setScreen]=useState('welcome');
 const [code,setCode]=useState('');
 const [phone,setPhone]=useState('');
 const [balance,setBalance]=useState(25000);
 const [history,setHistory]=useState([]);
 const [amount,setAmount]=useState('');
 const [recipient,setRecipient]=useState('');
 const [operator,setOperator]=useState('Orange Money');
 const [name,setName]=useState('Mon compte');
 useEffect(()=>{(async()=>{const h=await AsyncStorage.getItem('pc_history'); if(h)setHistory(JSON.parse(h)); const b=await AsyncStorage.getItem('pc_balance'); if(b)setBalance(Number(b)); const p=await AsyncStorage.getItem('pc_phone'); if(p)setPhone(p)})()},[]);
 const nav=useMemo(()=>screen==='dashboard'||screen==='send'||screen==='history'||screen==='profile',[screen]);
 const save=async(h,b)=>{setHistory(h);setBalance(b);await AsyncStorage.setItem('pc_history',JSON.stringify(h));await AsyncStorage.setItem('pc_balance',String(b));};
 const login=async()=>{if(code!==DEMO){Alert.alert('Code incorrect','Utilise le code démo 1234.');return} if(!phone.trim()) setPhone('0500000000'); await AsyncStorage.setItem('pc_phone',phone.trim()||'0500000000'); setScreen('dashboard');};
 const recharge=async()=>{const a=Number(amount); if(!recipient||!a||a<100){Alert.alert('Informations manquantes','Entre un numéro et un montant d’au moins 100 FCFA.');return} const item={id:Date.now(),type:'Recharge démo',recipient,operator,amount:a,status:'SUCCESS',date:new Date().toLocaleString('fr-FR')}; const h=[item,...history]; const b=balance+a; await save(h,b); setAmount(''); setRecipient(''); Alert.alert('Recharge réussie','Opération simulée — aucun argent réel.'); setScreen('dashboard');};
 const transfer=async()=>{const a=Number(amount); if(!recipient||!a||a<100){Alert.alert('Informations manquantes','Entre un numéro et un montant.');return} if(a>balance){Alert.alert('Solde insuffisant','Solde démo disponible : '+balance.toLocaleString('fr-FR')+' FCFA.');return} const item={id:Date.now(),type:'Transfert démo',recipient,operator,amount:-a,status:'SUCCESS',date:new Date().toLocaleString('fr-FR')}; const h=[item,...history]; const b=balance-a; await save(h,b); setAmount('');setRecipient('');Alert.alert('Transfert simulé','Aucun argent réel.');setScreen('dashboard');};
 const logout=async()=>{await AsyncStorage.clear();setBalance(25000);setHistory([]);setPhone('');setCode('');setScreen('welcome');};
 return <SafeAreaView style={styles.safe}><StatusBar style="light"/><ScrollView contentContainerStyle={styles.container}>
  <View style={styles.brand}><View style={styles.logo}><Text style={styles.logoText}>P</Text></View><Text style={styles.brandText}>Pay<Text style={{color:GREEN}}>Civo</Text></Text></View>
  {screen==='welcome'&&<><Text style={styles.heroTitle}>Envoyez de l'argent <Text style={{color:GREEN}}>rapidement</Text> et simplement</Text><Text style={styles.muted}>Version de démonstration pour tester le menu PayCivo avant les vrais paiements.</Text><Card><Text style={styles.balanceLabel}>Solde démo</Text><Text style={styles.big}>25 000 FCFA</Text><Text style={styles.muted}>Aucune opération financière réelle.</Text></Card><Button title="Créer un compte →" primary onPress={()=>setScreen('register')}/><Button title="Se connecter" onPress={()=>setScreen('login')}/></>}
  {(screen==='register'||screen==='login')&&<><Button title="← Retour" onPress={()=>setScreen('welcome')}/><Text style={styles.title}>{screen==='register'?'Créer un compte':'Se connecter'}</Text><Text style={styles.muted}>Version démo : aucun SMS réel n'est envoyé.</Text><Card><Text style={styles.label}>Numéro ivoirien</Text><TextInput value={phone} onChangeText={setPhone} placeholder="05 00 00 00 00" placeholderTextColor="#6e7e96" keyboardType="phone-pad" style={styles.input}/><Text style={styles.label}>Code démo</Text><TextInput value={code} onChangeText={setCode} placeholder="1234" placeholderTextColor="#6e7e96" keyboardType="number-pad" maxLength={4} style={styles.input}/><Text style={styles.demo}>CODE DÉMO : 1234</Text><Button title="Accéder au menu" primary onPress={login}/></Card></>}
  {screen==='dashboard'&&<><View style={styles.top}><Text style={styles.titleSmall}>Bienvenue 👋</Text><View style={styles.avatar}><Text>P</Text></View></View><Card><Text style={styles.balanceLabel}>Solde disponible</Text><Text style={styles.big}>{balance.toLocaleString('fr-FR')} FCFA</Text><Text style={styles.muted}>Compte de démonstration</Text></Card><View style={styles.grid}><Button title="➤  Envoyer" onPress={()=>setScreen('send')}/><Button title="↓  Recevoir" onPress={()=>setScreen('receive')}/><Button title="☷  Historique" onPress={()=>setScreen('history')}/></View><Button title="Profil" onPress={()=>setScreen('profile')}/></>}
  {screen==='send'&&<><Button title="← Retour" onPress={()=>setScreen('dashboard')}/><Text style={styles.title}>Transfert / Recharge</Text><Card><Text style={styles.label}>Opérateur</Text><Text style={styles.operator}>{operator}</Text><Text style={styles.label}>Numéro</Text><TextInput value={recipient} onChangeText={setRecipient} placeholder="05 00 00 00 00" placeholderTextColor="#6e7e96" keyboardType="phone-pad" style={styles.input}/><Text style={styles.label}>Montant FCFA</Text><TextInput value={amount} onChangeText={setAmount} placeholder="1000" placeholderTextColor="#6e7e96" keyboardType="number-pad" style={styles.input}/><Button title="📲 Simuler une recharge" primary onPress={recharge}/><Button title="💸 Simuler un transfert" onPress={transfer}/></Card></>}
  {screen==='receive'&&<><Button title="← Retour" onPress={()=>setScreen('dashboard')}/><Text style={styles.title}>Recevoir</Text><Card><Text style={styles.center}>Mon numéro</Text><Text style={styles.phone}>{phone||'0500000000'}</Text><Button title="Copier mon numéro" primary onPress={async()=>{await Clipboard.setStringAsync(phone||'0500000000');Alert.alert('Copié','Numéro copié.')}}/></Card></>}
  {screen==='history'&&<><Button title="← Retour" onPress={()=>setScreen('dashboard')}/><Text style={styles.title}>Historique</Text>{history.length===0?<Card><Text style={styles.muted}>Aucune opération.</Text></Card>:history.map(x=><Card key={x.id}><View style={styles.row}><View><Text style={styles.white}>{x.type}</Text><Text style={styles.muted}>{x.recipient} · {x.operator}</Text><Text style={styles.muted}>{x.date}</Text></View><Text style={[styles.amount,x.amount<0&&styles.danger]}>{x.amount>0?'+':''}{x.amount.toLocaleString('fr-FR')} F</Text></View></Card>)}</>}
  {screen==='profile'&&<><Button title="← Retour" onPress={()=>setScreen('dashboard')}/><Text style={styles.title}>Mon profil</Text><Card><View style={styles.avatarBig}><Text>P</Text></View><Text style={styles.center}>{name}</Text><Text style={styles.centerMuted}>{phone||'0500000000'}</Text><Button title="Se déconnecter" onPress={logout}/></Card></>}
  {nav&&<View style={styles.bottom}><TouchableOpacity onPress={()=>setScreen('dashboard')}><Text style={styles.bottomText}>⌂{`\n`}Accueil</Text></TouchableOpacity><TouchableOpacity onPress={()=>setScreen('send')}><Text style={styles.bottomText}>➤{`\n`}Envoyer</Text></TouchableOpacity><TouchableOpacity onPress={()=>setScreen('history')}><Text style={styles.bottomText}>☷{`\n`}Historique</Text></TouchableOpacity><TouchableOpacity onPress={()=>setScreen('profile')}><Text style={styles.bottomText}>●{`\n`}Profil</Text></TouchableOpacity></View>}
 </ScrollView></SafeAreaView>
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BG},container:{padding:22,paddingBottom:100},brand:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:28},logo:{width:44,height:44,borderRadius:14,backgroundColor:GREEN,alignItems:'center',justifyContent:'center'},logoText:{fontSize:24,fontWeight:'900',color:'#06111f'},brandText:{fontSize:26,fontWeight:'800',color:'#fff'},heroTitle:{fontSize:38,lineHeight:43,fontWeight:'800',color:'#fff',marginBottom:14},title:{fontSize:34,fontWeight:'800',color:'#fff',marginVertical:16},titleSmall:{fontSize:26,fontWeight:'800',color:'#fff'},muted:{color:MUTED,lineHeight:21,marginBottom:14},card:{backgroundColor:CARD,borderColor:LINE,borderWidth:1,borderRadius:22,padding:20,marginVertical:9},balanceLabel:{color:MUTED,fontSize:13},big:{fontSize:34,fontWeight:'800',color:'#fff',marginVertical:7},btn:{width:'100%',borderRadius:20,padding:17,marginVertical:7,borderWidth:1,borderColor:LINE,backgroundColor:CARD2,alignItems:'center'},primary:{backgroundColor:GREEN,borderColor:GREEN},btnText:{fontSize:17,fontWeight:'800',color:'#fff'},primaryText:{color:'#06111a'},label:{color:MUTED,fontSize:13,marginTop:8,marginBottom:7},input:{backgroundColor:'#08172b',borderColor:'#2a4160',borderWidth:1,borderRadius:14,color:'#fff',padding:15,fontSize:17,marginBottom:8},demo:{color:GREEN,textAlign:'center',fontSize:22,fontWeight:'900',letterSpacing:4,marginVertical:12},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},avatar:{width:42,height:42,borderRadius:21,backgroundColor:GREEN,alignItems:'center',justifyContent:'center'},avatarBig:{width:80,height:80,borderRadius:40,backgroundColor:GREEN,alignItems:'center',justifyContent:'center',alignSelf:'center',marginBottom:14},grid:{gap:8},operator:{color:'#fff',fontSize:17,backgroundColor:'#08172b',padding:15,borderRadius:14,marginBottom:10},center:{textAlign:'center',color:'#fff',fontSize:18,fontWeight:'700',marginVertical:7},centerMuted:{textAlign:'center',color:MUTED,marginBottom:12},phone:{textAlign:'center',color:GREEN,fontSize:30,fontWeight:'900',marginVertical:15},row:{flexDirection:'row',justifyContent:'space-between',gap:10},white:{color:'#fff',fontWeight:'700'},amount:{color:GREEN,fontWeight:'800'},danger:{color:'#ff7c8c'},bottom:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:'#071326',borderTopWidth:1,borderTopColor:LINE,flexDirection:'row',justifyContent:'space-around',paddingVertical:9},bottomText:{color:MUTED,textAlign:'center',fontSize:11}}
);
